### ISSUE TITLE
numDIDRequiredToAddTask populates field and disappears

### ISSUE THREAD

**Issue by RayKoren** [Distense/distense#218]
If this is just a question or you're not proposing something, erase the text you're reading and just create the issue.  You may also check out our FAQ if you have a question.

Thanks for your interest in Distense.

**If this is a bug report please let us know the details below**
![image](https://user-images.githubusercontent.com/16106956/36800160-058c2c20-1c6c-11e8-99a2-2a54838b23d9.png)
numDIDRequiredToAddTask populates field and disappears

What is the expected behavior?
numDIDRequiredToAddTask populates field and persists
Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.

OS: windows 10

Browser and version: chrome

Error output:

Page/function:

**If you're more officially proposing a task for Distense, please follow these rules**

*** Task Title Here (<= 70 chars or so) *** 

*** Link to task on Distense website *** 

Example: _https://disten.se/tasks/Show-which-network-connected-to-in-footer/1517543032517a7b124c0_

*** Task Spec *** 

_These are some guidelines we believe can make Distense more productive:_

1. Make the task as small as it can be but no smaller
2. Be as specific as possible
3. Keep the task title as short as possible
    - This will minimize the blockchain storage costs and the overall size of the Ethereum blockchain

Once you create a task here, and if you own enough DID, [add the task](https://disten.se/tasks/add) to our website.  
If you don't own enough DID to add the task (the number can be found [here](https://disten.se/tasks/add), ping John like so: @johnallen 
  and he will add the task to our website.  If you have no idea what we're talking about, read about [How Distense Works](https://disten.se/howitworks)

**Comment by JohnAllen** [comment]
Thanks for this @RayKoren -- on it and know what the problem is. 

If you wouldn't mind letting me know how you found Distense that would be awesome!

**Comment by RayKoren** [comment]
Stalking my Friend @bradford-hamilton on github ;)

**Comment by bradford-hamilton** [comment]
@RayKoren !! hahaha
