### ISSUE TITLE
Blank page on initial launch

### ISSUE THREAD

**Issue by 0xVolodya** [Distense/distense#228]
If this is just a question or you're not proposing something, erase the text you're reading and just create the issue.  You may also check out our FAQ if you have a question.

Thanks for your interest in Distense.

**If this is a bug report please let us know the details below**
Bug. Just downloaded project. Getting blank page/
What is the expected behavior?
Load content like in https://disten.se/
Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.

OS: 
ubuntu 16.04
Browser and version:
chrome

Error output:
The problem is in src/index.js. 

Changing in this file: await store.dispatch(fetchParameters()) ->  store.dispatch(fetchParameters())
solving the problem. Idk why this is happening.

**Comment by JohnAllen** [comment]
@nadalfederer Will check it out.  thanks for the report
