### ISSUE TITLE
The /pullrequests route throws an error

### ISSUE THREAD

**Issue by anshumanv** [Distense/distense#233]
`Unhandled Rejection (TypeError): Cannot read property 'getNumPullRequests' of undefined`

[This](https://github.com/Distense/distense-ui/blob/3820c60acf483bb69d7e6843b29cae0178ff6232/src/features/pullRequests/actions.js#L104) line apparently is causing it.

Please see if anyone is able to reproduce this issue.

**Comment by JohnAllen** [comment]
Will push a new version of `distense-contracts` soon that should fix this.
