### ISSUE TITLE
Write a bot that tweets new Distense tasks

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense#257]
Tasks are at this contract address [here](https://etherscan.io/address/0x1dbb1a04a826f803f526296058678006792ebc0f#code)

Should include:

- task title
- value in ETH|DID|USD
- Link to Github issue
- `rewardStatus`

**Comment by Sulejman** [comment]
What is the API feed for new tasks, is it from smart contract or somewhere in database?

**Comment by JohnAllen** [comment]
All our data is purely from smart contracts.

 - You'll probably want to import the Tasks contract [like this](https://github.com/Distense/distense-ui/blob/dev/src/contracts.js)
- You can get specific functions/data like [in this file](https://github.com/Distense/distense-ui/blob/228444aa81ef06897628c30f30f81403bd2e88b6/src/features/tasks/actions.js#L57)

Modifying the relevant functions in the last file, something like this should get you the tasks:

```
import * as contracts from './contracts'

export const fetchTasks = () => {
  // Have to get numTasks from chain to know how many to query by index
  try {
    const { getNumTasks } = await contracts.Tasks

    const numTasks = +await getNumTasks()
    console.log(`Found ${numTasks} tasks`)
    const tasks = await Promise.all(_.range(numTasks).map(getTaskByIndex))
  } catch (e) {
    console.error(e)
  }
}

const getTaskByIndex = async index => {
  let taskId
  try {
    const { taskIds } = await contracts.Tasks
    taskId = await taskIds(index)
  } catch (error) {
    console.log(`getTaskByIndex error: ${getTaskByIndex}`)
  }
  return getTaskByID(taskId)
}

export const getTaskByID = async taskId => {
  try {
    const { getTaskById } = await contracts.Tasks

    const contractTask = await getTaskById(taskId)
    // should have the task from chain here
  } catch (error) {
    console.error(error)
  }
}
```

**Comment by jacekv** [comment]
I will try to have a look into that over the weekend. We will see how much time I get :D But I think it is a cool task :P

**Comment by JohnAllen** [comment]
Hey @jacekv.  Think @Sulejman is working on this one already.  Why don't you give him a few days and maybe revisit if he can't get around to it?

Shortly we'll have claimable tasks.  Would be great to somehow show them as claimed in the UI.

**Comment by jacekv** [comment]
@JohnAllen  Are there any news regarding @Sulejman progress?

**Comment by JohnAllen** [comment]
no, closing
